package com.vivero.pickingve.ui.theme

import androidx.compose.ui.graphics.Color

// Brand colors
val BrandGreen = Color(0xFF025C65)
val BrandRed = Color(0xFF962622)
val BrandAmber = Color(0xFFB26A00)

// Warn tones (amber), acordes con la paleta corporativa verde/rojo
val LightWarnContainer = Color(0xFFFFE1B3)
val LightOnWarnContainer = Color(0xFF432A00)
val DarkWarnContainer = Color(0xFF5C4200)
val DarkOnWarnContainer = Color(0xFFFFE1B3)

// Marked border (amber), para líneas marcadas [M] de LINEA_PEDIDO (borde siempre visible)
val MarkedBorderColor = Color(0xFFFFC107)

// Picked tones (green), para líneas de pedido acopiadas
val LightPickedContainer = Color(0xFFD0E8DC)
val LightOnPickedContainer = Color(0xFF0A3B32)
val DarkPickedContainer = Color(0xFF1B4A3C)
val DarkOnPickedContainer = Color(0xFFD0E8DC)

// Light scheme
val LightPrimary = Color(0xFF025C65)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9DEFF8)
val LightOnPrimaryContainer = Color(0xFF001F24)
val LightSecondary = Color(0xFF4A6367)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8EC)
val LightOnSecondaryContainer = Color(0xFF051F23)
val LightTertiary = Color(0xFF545E7D)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDCE1FF)
val LightOnTertiaryContainer = Color(0xFF111B36)
val LightError = Color(0xFF962622)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD5)
val LightOnErrorContainer = Color(0xFF3E0000)
val LightBackground = Color(0xFFF4FAFB)
val LightOnBackground = Color(0xFF171D1E)
val LightSurface = Color(0xFFF4FAFB)
val LightOnSurface = Color(0xFF171D1E)
val LightSurfaceVariant = Color(0xFFDAE4E6)
val LightOnSurfaceVariant = Color(0xFF3F484A)
val LightOutline = Color(0xFF6F797B)
val LightOutlineVariant = Color(0xFFBEC8CA)
val LightSurfaceContainer = Color(0xFFE8EEF0)
val LightSurfaceContainerHigh = Color(0xFFE2E8EA)
val LightSurfaceContainerHighest = Color(0xFFDCE3E4)

// Dark scheme
val DarkPrimary = Color(0xFF6FD2DD)
val DarkOnPrimary = Color(0xFF00363D)
val DarkPrimaryContainer = Color(0xFF004F58)
val DarkOnPrimaryContainer = Color(0xFF9DEFF8)
val DarkSecondary = Color(0xFFB0CCD0)
val DarkOnSecondary = Color(0xFF1B3438)
val DarkSecondaryContainer = Color(0xFF324B4F)
val DarkOnSecondaryContainer = Color(0xFFCCE8EC)
val DarkTertiary = Color(0xFFBFC5E8)
val DarkOnTertiary = Color(0xFF27304C)
val DarkTertiaryContainer = Color(0xFF3D4764)
val DarkOnTertiaryContainer = Color(0xFFDCE1FF)
val DarkError = Color(0xFFFFB4AC)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF7B0A0D)
val DarkOnErrorContainer = Color(0xFFFFDAD5)
val DarkBackground = Color(0xFF0F1516)
val DarkOnBackground = Color(0xFFDDE3E4)
val DarkSurface = Color(0xFF0F1516)
val DarkOnSurface = Color(0xFFDDE3E4)
val DarkSurfaceVariant = Color(0xFF3F484A)
val DarkOnSurfaceVariant = Color(0xFFBEC8CA)
val DarkOutline = Color(0xFF889294)
val DarkOutlineVariant = Color(0xFF3F484A)
val DarkSurfaceContainer = Color(0xFF1B2122)
val DarkSurfaceContainerHigh = Color(0xFF252B2D)
val DarkSurfaceContainerHighest = Color(0xFF303637)